name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          plugin_music_token: ${{ secrets.LASTFM_API_KEY }}

          # Core Config
          user: evanbones
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Vancouver
          config_display: large
          
          # Activity Graph 
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Music (Last.fm)
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_user: evan_bones
          plugin_music_mode: recent
          plugin_music_limit: 2
          
          # Movies (Letterboxd)
          plugin_rss: yes
          plugin_rss_source: https://letterboxd.com/evanbones/rss/
          plugin_rss_limit: 2
